#!/usr/bin/ansible-playbook
- hosts: all
  become: yes
  any_errors_fatal: true
    
  tasks:

    - name: Remove IP address of all hosts to all hosts (to avoid duplicates)
      lineinfile:
        dest: /etc/hosts
        regexp: '.*{{ item }}$'
        line: "{{ hostvars[item].ansible_host }} {{item}}"
        state: absent
      when: hostvars[item].ansible_host is defined
      with_items: "{{ groups.all }}"

    - name: Add IP address of all hosts to all hosts
      lineinfile:
        dest: /etc/hosts
        regexp: '.*{{ item }}$'
        line: "{{ hostvars[item].ansible_host }} {{item}}"
        state: present
      when: hostvars[item].ansible_host is defined
      with_items: "{{ groups.all }}"